### ISSUE TITLE
Some attributes not loading correctly

### ISSUE THREAD

**Issue by adamsalter** [michael/ken-rb#3]
I have an example where it seems Ken is not loading the data correctly...

```
require 'pp'
require 'ken'
@resource = Ken.get('/en/metallica')
pp @resource.views # => various views, including '/music/musical_group'
pp @resource.attribute('/music/musical_group/member') # => nil, should be 7 values
pp Ken.session.mqlread(
    {:id => '/en/metallica',
      :'/music/musical_group/member' => [{}],
      :* => nil,
      :limit => 1
      }
    ) # => correctly shows musical group memberships
```

**Comment by adamsalter** [comment]
I'm seeing other 'odd' stuff, like

```
@resource = Ken.get('/en/metallica')
pp @resource.attributes # => various views, including /people/person
pp @resource.view('/people/person').attributes # => [] (empty??)
```

**Comment by michael** [comment]
For some reason the query Ken uses (based on reflection) does not provide the group memberships. It seems that /music/musical_group/member is some kind of a special link between objects. I have to admit that I don't fully understand how all that link stuff actually works. Even after carefully reading http://www.freebase.com/docs/mql/ch03.html#links :/

The result of the following query is the reason why musical group members are not available: 

```
{
  "id": "/en/metallica",
  "/type/reflect/any_master": [{
    "link": null,
    "name": null
  }],
  "/type/reflect/any_reverse": [{
    "link": null,
    "name": null
  }],
  "/type/reflect/any_value": [{
    "link":  null,
    "value": null
  }]
}​
```

See the result here: http://tinyurl.com/nju3v9

Unfortunately, time is so rare atm :(
Would be great if someone could help out and point me to the right direction.

**Comment by michael** [comment]
Reflection queries now use a high limit so that from now on we get the whole bunch of links (incoming and outgoing). Hopefully.

Furthermore you can now directly access individual types on a resource.
Usage: new_order.type('/music/artist') => #<Type id="/music/artist" name="Musical Artist">

Closed by 27b074ee6ea35cf4c5f9f2e90617fc9c2368558e

**Comment by michael** [comment]
```
@resource = Ken.get('/en/metallica')
pp @resource.attributes # => various views, including /people/person
pp @resource.view('/people/person').attributes # => [] (empty??)
```

Although metallica is a member of /people/person no attributes are set based on that type/view.

Available properties can now be discovered like so:
    pp @resource.type('/people/person').properties

**Comment by adamsalter** [comment]
Would it be possible to use paging to be sure all values were retrieved?

Something like this query (this doesn't work):

```
[{
  "link": null,
  "name": null,
  "limit": 20,
  "!/type/reflect/any_master": [{
    "id": "/en/metallica"
  }]
}]​
```

Unfortunately I don't understand MQL even as well as you do :/ Reflections can be quite confusing. ;)

Thanks for the update, and thanks again for a awesome library. I'll try it out.

**Comment by adamsalter** [comment]
I've just looked at the limit value you set... 99999

I think this will definitely get all values, but might time out. I guess if that ever happens we can look at it then ;) (e.g. paging)
